[train]
batch_size = 4
epochs = 40
learning_rate = 0.0002
beta1 = 0.5
beta2 = 0.999
seed = 42
workers = 4
lambda_pixel = 1.0
lambda_vgg = 2.0
lambda_adv = 2.0

[model]
num_channels = 3
hidden_channels = 64

[files]
image_size = 256
data_root = "images/train/"
output_dir = "models/"